#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")

env.coyote_sources = []

# Godot source files
env.add_source_files(env.coyote_sources, "*.cpp")

# Chain load SCsubs
SConscript("fpw/SCsub")
"""
SConscript("main/SCsub")
SConscript("gui/SCsub")
if not env["disable_3d"]:
    SConscript("3d/SCsub")
SConscript("2d/SCsub")
SConscript("animation/SCsub")
SConscript("audio/SCsub")
SConscript("resources/SCsub")
SConscript("debugger/SCsub")
SConscript("theme/SCsub")
"""

# Build it all as a library
lib = env.add_library("scene", env.coyote_sources)
env.Prepend(LIBS=[lib])
